export const verbes=[
   {
      "baseV":"abide",
      "pret":"abode",
      "pp":"abode",
      "trad":"respecter / se conformer à"
   },
   {
      "baseV":"arise",
      "pret":"arose",
      "pp":"arisen",
      "trad":"survenir"
   },
   {
      "baseV":"awake",
      "pret":"awoke",
      "pp":"awoken",
      "trad":"se réveiller"
   },
   {
      "baseV":"bear",
      "pret":"bore",
      "pp":"borne / born",
      "trad":"porter / supporter / naître"
   },
   {
      "baseV":"beat",
      "pret":"beat",
      "pp":"beaten",
      "trad":"battre"
   },
   {
      "baseV":"become",
      "pret":"became",
      "pp":"become",
      "trad":"devenir"
   },
   {
      "baseV":"beget",
      "pret":"begat / begot",
      "pp":"begotten",
      "trad":"engendrer"
   },
   {
      "baseV":"begin",
      "pret":"began",
      "pp":"begun",
      "trad":"commencer"
   },
   {
      "baseV":"bend",
      "pret":"bent",
      "pp":"bent",
      "trad":"plier / se courber"
   },
   {
      "baseV":"bet",
      "pret":"bet",
      "pp":"bet",
      "trad":"parier"
   },
   {
      "baseV":"bid",
      "pret":"bid / bade",
      "pp":"bid / bidden",
      "trad":"offrir"
   },
   {
      "baseV":"bite",
      "pret":"bit",
      "pp":"bitten",
      "trad":"mordre"
   },
   {
      "baseV":"bleed",
      "pret":"bled",
      "pp":"bled",
      "trad":"saigner"
   },
   {
      "baseV":"blow",
      "pret":"blew",
      "pp":"blown",
      "trad":"souffler / gonfler"
   },
   {
      "baseV":"break",
      "pret":"broke",
      "pp":"broken",
      "trad":"casser"
   },
   {
      "baseV":"bring",
      "pret":"brought",
      "pp":"brought",
      "trad":"apporter"
   },
   {
      "baseV":"broadcast",
      "pret":"broadcast",
      "pp":"broadcast",
      "trad":"diffuser / émettre"
   },
   {
      "baseV":"build",
      "pret":"built",
      "pp":"built",
      "trad":"construire"
   },
   {
      "baseV":"burn",
      "pret":"burnt / burned",
      "pp":"burnt / burned",
      "trad":"brûler"
   },
   {
      "baseV":"burst",
      "pret":"burst",
      "pp":"burst",
      "trad":"éclater"
   },
   {
      "baseV":"buy",
      "pret":"bought",
      "pp":"bought",
      "trad":"acheter"
   },
   {
      "baseV":"can",
      "pret":"could",
      "pp":"could",
      "trad":"pouvoir"
   },
   {
      "baseV":"cast",
      "pret":"cast",
      "pp":"cast",
      "trad":"jeter / distribuer (rôles)"
   },
   {
      "baseV":"catch",
      "pret":"caught",
      "pp":"caught",
      "trad":"attraper"
   },
   {
      "baseV":"chide",
      "pret":"chid / chode",
      "pp":"chid / chidden",
      "trad":"gronder"
   },
   {
      "baseV":"choose",
      "pret":"chose",
      "pp":"chosen",
      "trad":"choisir"
   },
   {
      "baseV":"cling",
      "pret":"clung",
      "pp":"clung",
      "trad":"s'accrocher"
   },
   {
      "baseV":"clothe",
      "pret":"clad / clothed",
      "pp":"clad / clothed",
      "trad":"habiller / recouvrir"
   },
   {
      "baseV":"come",
      "pret":"came",
      "pp":"come",
      "trad":"venir"
   },
   {
      "baseV":"cost",
      "pret":"cost",
      "pp":"cost",
      "trad":"coûter"
   },
   {
      "baseV":"creep",
      "pret":"crept",
      "pp":"crept",
      "trad":"ramper"
   },
   {
      "baseV":"cut",
      "pret":"cut",
      "pp":"cut",
      "trad":"couper"
   },
   {
      "baseV":"deal",
      "pret":"dealt",
      "pp":"dealt",
      "trad":"distribuer"
   },
   {
      "baseV":"dig",
      "pret":"dug",
      "pp":"dug",
      "trad":"creuser"
   },
   {
      "baseV":"dive",
      "pret":"dived",
      "pp":"dived / dove",
      "trad":"plonger"
   },
   {
      "baseV":"do",
      "pret":"did",
      "pp":"done",
      "trad":"faire"
   },
   {
      "baseV":"draw",
      "pret":"drew",
      "pp":"drawn",
      "trad":"dessiner / tirer"
   },
   {
      "baseV":"dream",
      "pret":"dreamt / dreamed",
      "pp":"dreamt / dreamed",
      "trad":"rêver"
   },
   {
      "baseV":"drink",
      "pret":"drank",
      "pp":"drunk",
      "trad":"boire"
   },
   {
      "baseV":"drive",
      "pret":"drove",
      "pp":"driven",
      "trad":"conduire"
   },
   {
      "baseV":"dwell",
      "pret":"dwelt",
      "pp":"dwelt / dwelled",
      "trad":"habiter"
   },
   {
      "baseV":"eat",
      "pret":"ate",
      "pp":"eaten",
      "trad":"manger"
   },
   {
      "baseV":"fall",
      "pret":"fell",
      "pp":"fallen",
      "trad":"tomber"
   },
   {
      "baseV":"feed",
      "pret":"fed",
      "pp":"fed",
      "trad":"nourrir"
   },
   {
      "baseV":"feel",
      "pret":"felt",
      "pp":"felt",
      "trad":"se sentir / ressentir"
   },
   {
      "baseV":"fight",
      "pret":"fought",
      "pp":"fought",
      "trad":"se battre"
   },
   {
      "baseV":"find",
      "pret":"found",
      "pp":"found",
      "trad":"trouver"
   },
   {
      "baseV":"flee",
      "pret":"fled",
      "pp":"fled",
      "trad":"s'enfuir"
   },
   {
      "baseV":"fling",
      "pret":"flung",
      "pp":"flung",
      "trad":"lancer"
   },
   {
      "baseV":"fly",
      "pret":"flew",
      "pp":"flown",
      "trad":"voler"
   },
   {
      "baseV":"forbid",
      "pret":"forbade",
      "pp":"forbidden",
      "trad":"interdire"
   },
   {
      "baseV":"forecast",
      "pret":"forecast",
      "pp":"forecast",
      "trad":"prévoir"
   },
   {
      "baseV":"foresee",
      "pret":"foresaw",
      "pp":"foreseen",
      "trad":"prévoir / presentir"
   },
   {
      "baseV":"forget",
      "pret":"forgot",
      "pp":"forgotten / forgot",
      "trad":"oublier"
   },
   {
      "baseV":"forgive",
      "pret":"forgave",
      "pp":"forgiven",
      "trad":"pardonner"
   },
   {
      "baseV":"forsake",
      "pret":"forsook",
      "pp":"forsaken",
      "trad":"abandonner"
   },
   {
      "baseV":"freeze",
      "pret":"froze",
      "pp":"frozen",
      "trad":"geler"
   },
   {
      "baseV":"get",
      "pret":"got",
      "pp":"gotten / got",
      "trad":"obtenir"
   },
   {
      "baseV":"give",
      "pret":"gave",
      "pp":"given",
      "trad":"donner"
   },
   {
      "baseV":"go",
      "pret":"went",
      "pp":"gone",
      "trad":"aller"
   },
   {
      "baseV":"grind",
      "pret":"ground",
      "pp":"ground",
      "trad":"moudre / opprimer"
   },
   {
      "baseV":"grow",
      "pret":"grew",
      "pp":"grown",
      "trad":"grandir / pousser"
   },
   {
      "baseV":"hang",
      "pret":"hung",
      "pp":"hung",
      "trad":"tenir / pendre"
   },
   {
      "baseV":"have",
      "pret":"had",
      "pp":"had",
      "trad":"avoir"
   },
   {
      "baseV":"hear",
      "pret":"heard",
      "pp":"heard",
      "trad":"entendre"
   },
   {
      "baseV":"hide",
      "pret":"hid",
      "pp":"hidden",
      "trad":"cacher"
   },
   {
      "baseV":"hit",
      "pret":"hit",
      "pp":"hit",
      "trad":"taper / appuyer"
   },
   {
      "baseV":"hold",
      "pret":"held",
      "pp":"held",
      "trad":"tenir"
   },
   {
      "baseV":"hurt",
      "pret":"hurt",
      "pp":"hurt",
      "trad":"blesser"
   },
   {
      "baseV":"keep",
      "pret":"kept",
      "pp":"kept",
      "trad":"garder"
   },
   {
      "baseV":"kneel",
      "pret":"knelt / knelled",
      "pp":"knelt / kneeled",
      "trad":"s'agenouiller"
   },
   {
      "baseV":"know",
      "pret":"knew",
      "pp":"known",
      "trad":"connaître / savoir"
   },
   {
      "baseV":"lay",
      "pret":"laid",
      "pp":"laid",
      "trad":"poser"
   },
   {
      "baseV":"lead",
      "pret":"led",
      "pp":"led",
      "trad":"mener / guider"
   },
   {
      "baseV":"lean",
      "pret":"leant / leaned",
      "pp":"leant / leaned",
      "trad":"s'incliner / se pencher"
   },
   {
      "baseV":"leap",
      "pret":"leapt / leaped",
      "pp":"leapt / leaped",
      "trad":"sauter / bondir"
   },
   {
      "baseV":"learn",
      "pret":"learnt",
      "pp":"learnt",
      "trad":"apprendre"
   },
   {
      "baseV":"leave",
      "pret":"left",
      "pp":"left",
      "trad":"laisser / quitter / partir"
   },
   {
      "baseV":"lend",
      "pret":"lent",
      "pp":"lent",
      "trad":"prêter"
   },
   {
      "baseV":"let",
      "pret":"let",
      "pp":"let",
      "trad":"permettre / louer"
   },
   {
      "baseV":"lie",
      "pret":"lay",
      "pp":"lain",
      "trad":"s'allonger"
   },
   {
      "baseV":"light",
      "pret":"lit / lighted",
      "pp":"lit / lighted",
      "trad":"allumer"
   },
   {
      "baseV":"lose",
      "pret":"lost",
      "pp":"lost",
      "trad":"perdre"
   },
   {
      "baseV":"make",
      "pret":"made",
      "pp":"made",
      "trad":"fabriquer"
   },
   {
      "baseV":"mean",
      "pret":"meant",
      "pp":"meant",
      "trad":"signifier"
   },
   {
      "baseV":"meet",
      "pret":"met",
      "pp":"met",
      "trad":"rencontrer"
   },
   {
      "baseV":"mow",
      "pret":"mowed",
      "pp":"mowed / mown",
      "trad":"tondre"
   },
   {
      "baseV":"offset",
      "pret":"offset",
      "pp":"offset",
      "trad":"compenser"
   },
   {
      "baseV":"overcome",
      "pret":"overcame",
      "pp":"overcome",
      "trad":"surmonter"
   },
   {
      "baseV":"partake",
      "pret":"partook",
      "pp":"partaken",
      "trad":"prendre part à"
   },
   {
      "baseV":"pay",
      "pret":"paid",
      "pp":"paid",
      "trad":"payer"
   },
   {
      "baseV":"plead",
      "pret":"pled / pleaded",
      "pp":"pled / pleaded",
      "trad":"supplier / plaider"
   },
   {
      "baseV":"preset",
      "pret":"preset",
      "pp":"preset",
      "trad":"programmer"
   },
   {
      "baseV":"prove",
      "pret":"proved",
      "pp":"proven / proved",
      "trad":"prouver"
   },
   {
      "baseV":"put",
      "pret":"put",
      "pp":"put",
      "trad":"mettre"
   },
   {
      "baseV":"quit",
      "pret":"quit",
      "pp":"quit",
      "trad":"quitter"
   },
   {
      "baseV":"read",
      "pret":"read",
      "pp":"read",
      "trad":"lire"
   },
   {
      "baseV":"relay",
      "pret":"relaid",
      "pp":"relaid",
      "trad":"relayer"
   },
   {
      "baseV":"rend",
      "pret":"rent",
      "pp":"rent",
      "trad":"déchirer"
   },
   {
      "baseV":"rid",
      "pret":"rid",
      "pp":"rid",
      "trad":"débarrasser"
   },
   {
      "baseV":"ring",
      "pret":"rang",
      "pp":"rung",
      "trad":"sonner / téléphoner"
   },
   {
      "baseV":"rise",
      "pret":"rose",
      "pp":"risen",
      "trad":"lever"
   },
   {
      "baseV":"run",
      "pret":"ran",
      "pp":"run",
      "trad":"courir"
   },
   {
      "baseV":"saw",
      "pret":"saw / sawed",
      "pp":"sawn / sawed",
      "trad":"scier"
   },
   {
      "baseV":"say",
      "pret":"said",
      "pp":"said",
      "trad":"dire"
   },
   {
      "baseV":"see",
      "pret":"saw",
      "pp":"seen",
      "trad":"voir"
   },
   {
      "baseV":"seek",
      "pret":"sought",
      "pp":"sought",
      "trad":"chercher"
   },
   {
      "baseV":"sell",
      "pret":"sold",
      "pp":"sold",
      "trad":"vendre"
   },
   {
      "baseV":"send",
      "pret":"sent",
      "pp":"sent",
      "trad":"envoyer"
   },
   {
      "baseV":"set",
      "pret":"set",
      "pp":"set",
      "trad":"fixer"
   },
   {
      "baseV":"shake",
      "pret":"shook",
      "pp":"shaken",
      "trad":"secouer"
   },
   {
      "baseV":"shed",
      "pret":"shed",
      "pp":"shed",
      "trad":"répandre / laisser tomber"
   },
   {
      "baseV":"shine",
      "pret":"shone",
      "pp":"shone",
      "trad":"briller"
   },
   {
      "baseV":"shoe",
      "pret":"shod",
      "pp":"shod",
      "trad":"chausser"
   },
   {
      "baseV":"shoot",
      "pret":"shot",
      "pp":"shot",
      "trad":"tirer / fusiller"
   },
   {
      "baseV":"show",
      "pret":"showed",
      "pp":"shown",
      "trad":"montrer"
   },
   {
      "baseV":"shut",
      "pret":"shut",
      "pp":"shut",
      "trad":"fermer"
   },
   {
      "baseV":"sing",
      "pret":"sang",
      "pp":"sung",
      "trad":"chanter"
   },
   {
      "baseV":"sink",
      "pret":"sank / sunk",
      "pp":"sunk / sunken",
      "trad":"couler"
   },
   {
      "baseV":"sit",
      "pret":"sat",
      "pp":"sat",
      "trad":"s'asseoir"
   },
   {
      "baseV":"slay",
      "pret":"slew",
      "pp":"slain",
      "trad":"tuer"
   },
   {
      "baseV":"sleep",
      "pret":"slept",
      "pp":"slept",
      "trad":"dormir"
   },
   {
      "baseV":"slide",
      "pret":"slid",
      "pp":"slid",
      "trad":"glisser"
   },
   {
      "baseV":"slit",
      "pret":"slit",
      "pp":"slit",
      "trad":"fendre"
   },
   {
      "baseV":"smell",
      "pret":"smelt",
      "pp":"smelt",
      "trad":"sentir"
   },
   {
      "baseV":"sow",
      "pret":"sowed",
      "pp":"sown / sowed",
      "trad":"semer"
   },
   {
      "baseV":"speak",
      "pret":"spoke",
      "pp":"spoken",
      "trad":"parler"
   },
   {
      "baseV":"speed",
      "pret":"sped",
      "pp":"sped",
      "trad":"aller vite"
   },
   {
      "baseV":"spell",
      "pret":"spelt",
      "pp":"spelt",
      "trad":"épeler / orthographier"
   },
   {
      "baseV":"spend",
      "pret":"spent",
      "pp":"spent",
      "trad":"dépenser / passer du temps"
   },
   {
      "baseV":"spill",
      "pret":"spilt / spilled",
      "pp":"spilt / spilled",
      "trad":"renverser"
   },
   {
      "baseV":"spin",
      "pret":"spun",
      "pp":"spun",
      "trad":"tourner / faire tourner"
   },
   {
      "baseV":"spit",
      "pret":"spat / spit",
      "pp":"spat / spit",
      "trad":"cracher"
   },
   {
      "baseV":"split",
      "pret":"split",
      "pp":"split",
      "trad":"fendre"
   },
   {
      "baseV":"spoil",
      "pret":"spoilt",
      "pp":"spoilt",
      "trad":"gâcher / gâter"
   },
   {
      "baseV":"spread",
      "pret":"spread",
      "pp":"spread",
      "trad":"répandre"
   },
   {
      "baseV":"spring",
      "pret":"sprang",
      "pp":"sprung",
      "trad":"surgir / jaillir / bondir"
   },
   {
      "baseV":"stand",
      "pret":"stood",
      "pp":"stood",
      "trad":"être debout"
   },
   {
      "baseV":"steal",
      "pret":"stole",
      "pp":"stolen",
      "trad":"voler / dérober"
   },
   {
      "baseV":"stick",
      "pret":"stuck",
      "pp":"stuck",
      "trad":"coller"
   },
   {
      "baseV":"sting",
      "pret":"stung",
      "pp":"stung",
      "trad":"piquer"
   },
   {
      "baseV":"stink",
      "pret":"stank",
      "pp":"stunk",
      "trad":"puer"
   },
   {
      "baseV":"strew",
      "pret":"strewed",
      "pp":"strewn / strewed",
      "trad":"éparpiller"
   },
   {
      "baseV":"strike",
      "pret":"struck",
      "pp":"stricken / struck",
      "trad":"frapper"
   },
   {
      "baseV":"strive",
      "pret":"strove",
      "pp":"striven",
      "trad":"s'efforcer"
   },
   {
      "baseV":"swear",
      "pret":"swore",
      "pp":"sworn",
      "trad":"jurer"
   },
   {
      "baseV":"sweat",
      "pret":"sweat / sweated",
      "pp":"sweat / sweated",
      "trad":"suer"
   },
   {
      "baseV":"sweep",
      "pret":"swept",
      "pp":"swept",
      "trad":"balayer"
   },
   {
      "baseV":"swell",
      "pret":"swelled / sweated",
      "pp":"swollen",
      "trad":"gonfler / enfler"
   },
   {
      "baseV":"swim",
      "pret":"swam",
      "pp":"swum",
      "trad":"nager"
   },
   {
      "baseV":"swing",
      "pret":"swung",
      "pp":"swung",
      "trad":"se balancer"
   },
   {
      "baseV":"take",
      "pret":"took",
      "pp":"taken",
      "trad":"prendre"
   },
   {
      "baseV":"teach",
      "pret":"taught",
      "pp":"taught",
      "trad":"enseigner"
   },
   {
      "baseV":"tear",
      "pret":"tore",
      "pp":"torn",
      "trad":"déchirer"
   },
   {
      "baseV":"tell",
      "pret":"told",
      "pp":"told",
      "trad":"dire / raconter"
   },
   {
      "baseV":"think",
      "pret":"thought",
      "pp":"thought",
      "trad":"penser"
   },
   {
      "baseV":"thrive",
      "pret":"throve / thrived",
      "pp":"thriven / thrived",
      "trad":"prospérer"
   },
   {
      "baseV":"throw",
      "pret":"threw",
      "pp":"thrown",
      "trad":"jeter"
   },
   {
      "baseV":"thrust",
      "pret":"thrust",
      "pp":"thrust",
      "trad":"enfoncer"
   },
   {
      "baseV":"typeset",
      "pret":"typeset",
      "pp":"typeset",
      "trad":"composer"
   },
   {
      "baseV":"undergo",
      "pret":"underwent",
      "pp":"undergone",
      "trad":"subir"
   },
   {
      "baseV":"understand",
      "pret":"understood",
      "pp":"understood",
      "trad":"comprendre"
   },
   {
      "baseV":"wake",
      "pret":"woke",
      "pp":"woken",
      "trad":"réveiller"
   },
   {
      "baseV":"weep",
      "pret":"wept",
      "pp":"wept",
      "trad":"pleurer"
   },
   {
      "baseV":"wet",
      "pret":"wet / wetted",
      "pp":"wet / wetted",
      "trad":"mouiller"
   },
   {
      "baseV":"win",
      "pret":"won",
      "pp":"won",
      "trad":"gagner"
   },
   {
      "baseV":"wind",
      "pret":"wound",
      "pp":"wound",
      "trad":"enrouler / remonter"
   },
   {
      "baseV":"withdraw",
      "pret":"withdrew",
      "pp":"withdrawn",
      "trad":"se retirer"
   },
   {
      "baseV":"wring",
      "pret":"wrung",
      "pp":"wrung",
      "trad":"tordre"
   },
   {
      "baseV":"write",
      "pret":"wrote",
      "pp":"written",
      "trad":"écrire"
   }
]